/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef struct Workspace Workspace;

struct Workspace *create_workspace(const char *name, const char *path);

void destroy_workspace(struct Workspace *workspace);

const char *const *workspace_files(const struct Workspace *workspace);
